Don't use accompanied libpq on OS X (darwin) when libpq is found elsewhere

diff --git a/trunk/RPostgreSQL/configure.in b/trunk/RPostgreSQL/configure.in
--- a/trunk/RPostgreSQL/configure.in
+++ b/trunk/RPostgreSQL/configure.in
@@ -19,9 +19,12 @@ case "${host_os}" in
     ;;
 esac
 
-# Check for non-standard programs: pg_configg(1) to configure PostgreSQL builds
+
+# Check for non-standard programs: pg_config(1) to configure PostgreSQL builds
 AC_PATH_PROG([PG_CONFIG], [pg_config])
 
+# By default, we will not use the accompanied libpq 
+ENABLE_LIBPQ=
 
 # If pg_config was found, let's use it
 if test "${PG_CONFIG}" != ""; then
@@ -100,23 +103,12 @@ else
 	    fi
 	done
     fi
-fi
-
-# Expand into arguments
-PKG_CPPFLAGS="-I${PG_INCDIR}"
-PKG_LIBS="-L${PG_LIBDIR} -lpq"
-# Test for sanity by looking for libpq-fe.h, no explicit action on found, error on failure
-AC_CHECK_FILE(["${PG_INCDIR}/libpq-fe.h"],
-	,
-	AC_SUBST(R_OS_TYPE))
-
-# Now substitute these two variable in src/Makevars.in to create src/Makevars
-AC_SUBST(PKG_CPPFLAGS)
-AC_SUBST(PKG_LIBS)
-
-ENABLE_LIBPQ=
-if test "$R_OS_TYPE" = "darwin" ; then
-ENABLE_LIBPQ='
+    if ! test $PG_LIBDIR
+    then
+        if test "$R_OS_TYPE" = "darwin" ; then
+# in case we cannot find any libpq library we will use the accompanied libpq
+# This content would be written into src/Makevars at the end of this script
+            ENABLE_LIBPQ='
 
 PKG_CPPFLAGS=-Ilibpq
 PKG_LIBS=libpq/libpq.a
@@ -131,7 +123,21 @@ libpq/libpq.5.dylib:
 clean:
 	(cd libpq; $(MAKE) -f Makefile.darwin clean)
 '
+        fi
+    fi
 fi
+
+# Expand into arguments
+PKG_CPPFLAGS="-I${PG_INCDIR}"
+PKG_LIBS="-L${PG_LIBDIR} -lpq"
+# Test for sanity by looking for libpq-fe.h, no explicit action on found, error on failure
+AC_CHECK_FILE(["${PG_INCDIR}/libpq-fe.h"],
+	,
+	AC_SUBST(R_OS_TYPE))
+
+# Now substitute these two variable in src/Makevars.in to create src/Makevars
+AC_SUBST(PKG_CPPFLAGS)
+AC_SUBST(PKG_LIBS)
 
 AC_SUBST(ENABLE_LIBPQ)
 AC_OUTPUT(src/Makevars)
